project:
  type: book
  output-dir: docs

book:
  title: "Probabilistic Modeling and Statistical Computing"
  author: "Jeff Jacobs"
  date: last-modified
  # navbar:
  #   title: "PMSC"
  #   background: primary
  #   search: false
  #   left:
  #     - text: "Home"
  #       file: index.qmd
  #     - talks.qmd
  #     - about.qmd 
  chapters:
    - index.qmd
    - 00-intro.qmd
    - part: "Data Science Workflow"
      chapters:
        - 01-ds-tools.qmd
        - 02-data-gathering.qmd
    - part: "Data Cleaning and Analysis"
      chapters:
        - 03-data-cleaning.qmd
        - 04-eda.qmd
    - part: "Machine Learning Fundamentals"
      chapters:
        - 05-optimization.qmd
        - 06-classification.qmd
    - part: "Machine Learning Algorithms"
      chapters:
        - 07-classification-algs.qmd
        - 08-neural-nets.qmd
        - 09-unsupervised.qmd
    - part: "Applications"
      chapters:
        - 10-network-data.qmd
        - 11-image-data.qmd
        - 12-nlp.qmd
    - 13-conclusion.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



