project:
  type: book
  output-dir: docs
  preview:
    port: 4000

book:
  title: "Data Science Without Fear"
  author: "Jeff Jacobs"
  date: last-modified
  # navbar:
  #   title: "PMSC"
  #   background: primary
  #   search: false
  #   left:
  #     - text: "Home"
  #       file: index.qmd
  #     - talks.qmd
  #     - about.qmd 
  chapters:
    - index.qmd
    - ch01.qmd
    - part: "Data Science Workflow"
      chapters:
        - ch02.qmd
        - ch03.qmd
    - part: "Data Cleaning and Analysis"
      chapters:
        - ch04.qmd
        - ch05.qmd
    - part: "Machine Learning Fundamentals"
      chapters:
        - ch06.qmd
        - ch07.qmd
    - part: "Machine Learning Algorithms"
      chapters:
        - ch08.qmd
        - ch09.qmd
        - ch10.qmd
    - part: "Applications"
      chapters:
        - ch11.qmd
        - ch12.qmd
        - ch13.qmd
    - ch14.qmd
    - references.qmd
  appendices:
    - resources.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



